### ISSUE TITLE
JSON Data

### ISSUE THREAD

**Issue by PrinceEntree8** [cristianlivella/ArgoAPI#1]
Ciao, ho visto che decodifichi un file json per ottenere i dati da argo. Io non sono un esperto di PHP e vorrei fare un parse di json, ma dove lo trovo dal sito?

**Comment by PrinceEntree8** [comment]
Mi restituisce 405

**Comment by cristianlivella** [comment]
Quello è l'url base, poi varia in base ai dati che vuoi ottenere.
Per esempio per effettuare il login, dovrai effettuare una richiesta get a questo url: https://www.portaleargo.it/famiglia/api/rest/login, inserendo nell'header della richiesta i seguenti parametri (oltre agli header "standard" per tutte le richiesta al server Argo, vedi sotto):
x-cod-min (codice scuola)
x-user-id (username)
x-pwd (password)
Dovrebbe restituirti un json con il token, che ti servirà per tutte le altre richieste.

Questi sono gli header standard attuali (è possibile che col tempo vengano cambiati da Argo), che dovrai inserire in ogni richiesta, altrimenti riceverai un errore 500:
x-key-app: ax6542sdru3217t4eesd9
x-version: 2.0.2
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Se mi spieghi meglio cosa vuoi fare, e in che linguaggio, posso provare ad aiutarti.
Ti lascio la mia email: cristian@cristianlivella.com

**Comment by PrinceEntree8** [comment]
Grazie mille!

**Comment by PrinceEntree8** [comment]
Ciao, in questa linea di codice
`$header = array("x-auth-token: ".$this->authToken, "x-cod-min: ".$this->codMin, "x-prg-alunno: ".$this->prgAlunno,`
'prgAlunno' non saprei cosa sia perché non trovo nessuna dichiarazione

**Comment by cristianlivella** [comment]
Dalla riga 42 alla 45 viene decodificato il json di risposta dal server argo in un array, e tutti gli elementi di quell'array vengono inseriti nella variabile `$this`.

Quindi, nella risposta al login, troverai anche `prgAlunno`
