### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by FrancescoZa** [cristianlivella/ArgoAPI#4]
Salve.
Sto cercando di visualizzare i compiti assegnati, fin qui tutto ok, ma inserendo come limite del ciclo for la lunghezza dell'array ottengo i dati fino a Febbraio. Non dovrei ottenere i compiti assegnati durante tutto l'anno?

Questo è il codice interessato:
`$request = $argo->compiti();
      for($i=0;$i<sizeof($request);$i++){
      $data= $request[$i]['datGiorno'];
      echo $data;
    }`

Spero che mi possa aiutare in questo piccolo problema, buon proseguimento di giornata.

**Comment by cristianlivella** [comment]
Ciao. Scusa se rispondo solo ora ma non avevo ricevuto la notifica.

Purtroppo questo non è un piccolo problema, ma è probabilmente il problema più grande di queste API. Argo le ha progettate per essere utilizzate con la loro applicazione ufficiale, che visualizza al massimo 100 elementi per ogni richiesta, quindi anche il server restituisce soltanto 100 elementi.
